project_name: gocb-opentelemetry-tracing

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - skip: true

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: hcelaloner
    name: gocb-opentelemetry-tracing